[package]
name = "nuklear-sys"
version = "0.1.0"
authors = ["greedengineer <greedengineer4321@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
